apiVersion: apps/v1
kind: Deployment
metadata:
  name: s09s12-web
spec:
  replicas: 1
  selector:
    matchLabels: { app: s09s12-web }
  template:
    metadata:
      labels: { app: s09s12-web }
    spec:
      containers:
        - name: web
          image: s09s12-app::v1.0.0 
          ports: [{ containerPort: 8080 }]
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true   
            allowPrivilegeEscalation: false        
          resources: {}             # no limits/requests
